### PR TITLE
Testing label merges

### PR DESCRIPTION
**Pull request by brianbao**
@jlafleche

### CODE REVIEW

**Comment by jlafleche** [comment]
what does this mean?

**Comment by brianbao** [comment]
We'll auto-merge if you LGTM, CircleCI is passing, and the label is on. Don't LGTM yet though it's not implemented.

**Comment by jlafleche** [comment]
LGTḾ!

**Comment by jlafleche** [comment]
jk - lgtɱ

**Comment by jlafleche** [comment]
lgtɯ

**Comment by jlafleche** [comment]
ok ok lgtṃ

**Comment by jlafleche** [comment]
(lgtm)

**Comment by brianbao** [comment]
:+1:

**Pull request merged**
