### PR TITLE
Revert "Revert "Revert "Revert "Revert "Revert "Revert "Testing merge poller"""""""

### PR DESCRIPTION
**Pull request by jlafleche**
Reverts jlafleche/sauron-demo#22

### CODE REVIEW

**Comment by brianbao** [comment]
:-1:

**Comment by jlafleche** [comment]
LGTM

**Comment by brianbao** [comment]
ŁGTM

**Comment by brianbao** [comment]
Looks good.

**Comment by brianbao** [comment]
Not bad son.

**Comment by brianbao** [comment]
LGTM

**Comment by jlafleche** [comment]
winning.

**Comment by brianbao** [comment]
:+1:

**Pull request merged**
