### PR TITLE
Test 1

### PR DESCRIPTION
**Pull request by brianbao**
@jlafleche Testing Kinesis implementation.

### CODE REVIEW

**Comment by brianbao** [comment]
Don't LGTM yet.

**Comment by brianbao** [comment]
Test

**Comment by jlafleche** [comment]
logtm

**Comment by brianbao** [comment]
YOU'RE BANNED

**Comment by jlafleche** [comment]
LoTR

**Comment by jlafleche** [comment]
fuck
:-1:
plus one

**Comment by jlafleche** [comment]
Looks Great To Me!

Ship it!

**Comment by jlafleche** [comment]
Go ahead and merge @brianbao

**Comment by jlafleche** [comment]
why isn't this merged yet?

**Comment by jlafleche** [comment]
lgtm

**Comment by brianbao** [comment]
So this is what it must feel like to be Usman

**Comment by zenkeemy** [comment]
@jlafleche: @usmanghani would be proud

**Pull request merged**
